#!/usr/bin/python
import sys, urllib2, json, pymongo, ast
from pymongo import MongoClient
from bson import json_util
from bson.json_util import loads,dumps
import collections
import urllib

connection = MongoClient('localhost', 27017)
###Getting the DATABASE###
db = connection.test5
###Getting the Collection###
collection = db.zip_code
zip_code=db.zip_code

myurl = "http://media.mongodb.org/zips.json?_ga=1.14351159.1075586396.1434399762"

response = urllib2.urlopen(myurl)
data = response.read()

testfile = urllib.URLopener()
testfile.retrieve(myurl, "file.json")
file = 'file.json'
with open(file, 'r') as f:
    for line in f:
	jsonWord = json.loads(line)
	dict = {}
	list = []
	for type in jsonWord:
		print type, jsonWord[type]
		dict[type] = jsonWord[type]
	list.append(ast.literal_eval(json.dumps(dict)))
	result = zip_code.insert_one(dict)
